//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditorias
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
        public int usuario_id { get; set; }
        public Nullable<byte> estatus { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
