//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class videojuegos_db : DbContext
    {
        public videojuegos_db()
            : base("name=videojuegos_db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auditorias> auditorias { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<inventarios> inventarios { get; set; }
        public virtual DbSet<rentas> rentas { get; set; }
        public virtual DbSet<rentas_detalles> rentas_detalles { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<videojuegos> videojuegos { get; set; }
    }
}
