//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventarios
    {
        public int id { get; set; }
        public int videojuego_id { get; set; }
        public int existencias { get; set; }
        public Nullable<byte> estatus { get; set; }
    
        public virtual videojuegos videojuegos { get; set; }
    }
}
