//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rentas()
        {
            this.rentas_detalles = new HashSet<rentas_detalles>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int usuario_id { get; set; }
        public int cliente_id { get; set; }
        public Nullable<byte> estatus { get; set; }
        public decimal total { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentas_detalles> rentas_detalles { get; set; }
    }
}
